### ISSUE TITLE
Update colors when variable value changes

### ISSUE THREAD

**Issue by briandconnelly** [yoavram/Plato#5]
If I change Strain 1 to Strain "WT", for example, the color in the wells with value 1 isn't removed

**Comment by yoavram** [comment]
It works on well on Chrome/Win7:

![2015-05-06_07-45-17](https://cloud.githubusercontent.com/assets/1288133/7487651/1c77844e-f3c4-11e4-9c49-c0e85c678358.png)

so I thought this is another Safari-specific bug.
But running on [browserstack](https://www.browserstack.com/) with Safari8/Yosemite:

![bs_macyos_safari_8 0 1](https://cloud.githubusercontent.com/assets/1288133/7487671/875003e0-f3c4-11e4-8e4a-6e398f13a364.jpg)

seems to work fine. Note that the wells are updated only after you change focus -- that is, if you change 1 to wt it will only update after you click anywhere else on the screen. Also, if there are duplicates then it doesn't update.

Does that make sense or are you expiriencing something different?

**Comment by briandconnelly** [comment]
Hmm, I had thought I was having this problem, started making the issue, and realized it was ok. Must have accidentally still submitted it. Sorry!

**Comment by yoavram** [comment]
No problem, thanks!
