### ISSUE TITLE
Clear button

### ISSUE THREAD

**Issue by briandconnelly** [yoavram/Plato#8]
Having the plate filled out at the beginning is nice to demonstrate how Plato can be used, but it takes quite a while to clear the plate if I wanted to make a completely different layout. What do you think about adding a button to quickly clear all wells and variables?

**Comment by yoavram** [comment]
Relates to #9, would clearing make all wells "0" or ""?

**Comment by briandconnelly** [comment]
My personal preference would be "". I think nothingness contrasts more sharply with strain labels than a 0 label.

**Comment by yoavram** [comment]
Agree. So as you suggest in #9, empty wells will not be downloaded and the clear button will make all wells empty (i.e. "").
