### ISSUE TITLE
Download button doesn't work if any wells are empty

### ISSUE THREAD

**Issue by briandconnelly** [yoavram/Plato#9]
If any of the wells are empty, the download button does not work for me (Safari or Firefox 38). Seems important, since I know people often do experiments that do not use the entire plate.

...maybe this was my problem with the download button earlier

**Comment by yoavram** [comment]
Would you have empty wells appear as "0" or just as ""?

**Comment by briandconnelly** [comment]
As with #8, "" would be what I would do.

Similarly, I'd not include any empty wells in the output, or at least make that an option.

**Comment by yoavram** [comment]
Agree. So empty wells ("") will not be downloaded.
I'll also add a test that "empties" a well and then clicks download to verify that this but is fixed.

**Comment by yoavram** [comment]
Fixed in commit 196cc0f801d3c385211bc2db950cd80a98f11554
